version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - xscan-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./results:/app/results
      - ./xscan:/app/xscan
      - ./tools:/app/tools
      - ./backend/config.json:/app/config.json
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - xscan-net

networks:
  xscan-net:
    driver: bridge
